INSERT INTO pais VALUES 
	(1,'USA','USA'),
	(2,'Canada','CAN'),
	(3,'Reino Unido','GBR'),
	(4,'Afeganistão','AFG'),
	(5,'Albânia','ALB'),
	(6,'Argélia','DZA'),
	(7,'Samoa Americana','ASM'),
	(8,'Andorra','AND'),
	(9,'Angola','AGO'),
	(10,'Anguilla','AIA'),
	(11,'Antígua e Barbuda','ATG'),
	(12,'Argentina','ARG'),
	(13,'Armênia','ARM'),
	(14,'Aruba','ABW'),
	(15,'Ilha de Ascensão','ASC'),
	(16,'Austrália','AUS'),
	(17,'Austria','AUT'),
	(18,'Azerbaijão','AZE'),
	(19,'Bahamas','BHS'),
	(20,'Bahrein','BHR'),
	(21,'Bangladeche','BGD'),
	(22,'Barbados','BRB'),
	(23,'Belorússia','BLR'),
	(24,'Bélgica','BEL'),
	(25,'Belize','BLZ'),
	(26,'Benin','BEN'),
	(27,'Bermuda','BMU'),
	(28,'Butão','BTN'),
	(29,'Bolívia','BOL'),
	(30,'Bósnia e Herzegovina','BIH'),
	(31,'Botsuana','BWA'),
	(32,'Brasil','BRA'),
	(33,'Território Britânico do Oceano Índico','IOT'),
	(34,'Brunei','BRN'),
	(35,'Bulgária','BGR'),
	(36,'Burquina Faso','BFA'),
	(37,'Burma','BUR'),
	(38,'Burundi','BDI'),
	(39,'Camarões','CMR'),
	(40,'Camboja','KHM'),
	(42,'Cabo Verde','CPV'),
	(43,'Ilhas Cayman','CYM'),
	(44,'República Centro-Africana','CAF'),
	(45,'Chade','TCD'),
	(46,'Chile','CHL'),
	(47,'China','CHN'),
	(48,'Ilhas Christmas','CXR'),
	(49,'Ilhas Cocos (Keeling)','CCK'),
	(50,'Colômbia','COL'),
	(51,'Ilhas Comores','COM'),
	(52,'Congo','COD'),
	(53,'Ilhas Cook','COK'),
	(54,'Costa Rica','CRI'),
	(55,'Côte dIvoire (Costa do Marfim)','CIV'),
	(56,'Croácia','HRV'),
	(57,'Cuba','CUB'),
	(58,'Chipre','CYP'),
	(59,'República Tcheca','CZE'),
	(60,'Dinamarca','DNK'),
	(61,'Jibuti','DJI'),
	(62,'Domínica','DMA'),
	(63,'República Dominicana','DOM'),
	(64,'Equador','ECU'),
	(65,'Egito','EGY'),
	(66,'El Salvador','SLV'),
	(67,'Guiné Equatorial','GNQ'),
	(68,'Eritréia','ERI'),
	(69,'Estônia','EST'),
	(70,'Etiópia','ETH'),
	(71,'Ilhas Malvinas (Falkland)','FLK'),
	(72,'Ilhas Faroés','FRO'),
	(73,'Micronésia','FSM'),
	(74,'Fiji','FJI'),
	(75,'Finlândia','FIN'),
	(76,'França','FRA'),
	(77,'Guiana Francesa','GUF'),
	(78,'Polinésia Francesa','PYF'),
	(79,'Gabão','GAB'),
	(80,'Faixa de Gaza','GZA'),
	(81,'Geórgia','GEO'),
	(82,'Alemanha','DEU'),
	(83,'Gana','GHA'),
	(84,'Gibraltar','GIB'),
	(85,'Grécia','GRC'),
	(86,'Groenlândia','GRL'),
	(87,'Granada','GRD'),
	(88,'Guadeloupe','GLP'),
	(89,'Guão','GUM'),
	(90,'Guatemala','GTM'),
	(91,'Guiné','GIN'),
	(92,'Guiné-Bissau','GNB'),
	(93,'Guiana','GUY'),
	(94,'Haiti','HTI'),
	(95,'Santa Sé','VAT'),
	(96,'Honduras','HND'),
	(97,'Hong Kong S.A.R.','HKG'),
	(98,'Hungria','HUN'),
	(99,'Islândia','ISL'),
	(100,'India','IND'),
	(101,'Indonésia','IDN'),
	(102,'Irã','IRN'),
	(103,'Iraque','IRQ'),
	(104,'Irlanda','IRL'),
	(105,'Ilha de Man','IMN'),
	(106,'Israel','ISR'),
	(107,'Itália','ITA'),
	(108,'Jamaica','JAM'),
	(109,'Japão','JPN'),
	(110,'Ilha Jarvis','JVI'),
	(111,'Jordânia','JOR'),
	(112,'Cazaquistão','KAZ'),
	(113,'Quênia','KEN'),
	(114,'Kiribati','KIR'),
	(115,'Coreia do Sul','Korea'),
	(116,'Kuwait','KWT'),
	(117,'Quirguistão','KGZ'),
	(118,'Laos','LAO'),
	(119,'Letônia','LVA'),
	(120,'Líbano','LBN'),
	(121,'Lesoto','LSO'),
	(122,'Libéria','LBR'),
	(123,'Líbia','LBY'),
	(124,'Listenstaine','LIE'),
	(125,'Lituânia','LTU'),
	(126,'Luxemburgo','LUX'),
	(127,'Macau','MAC'),
	(128,'Macedônia','MKD'),
	(129,'Madagascar','MDG'),
	(130,'Malávi','MWI'),
	(131,'Malasia','MYS'),
	(132,'Maldivas','MDV'),
	(133,'Mali','MLI'),
	(134,'Malta','MLT'),
	(135,'Ilhas Marshall','MHL'),
	(136,'Martinica','MTQ'),
	(137,'Mauritânia','MRT'),
	(138,'Maurício','MUS'),
	(139,'Mayotte','MYT'),
	(140,'Mexico','MEX'),
	(141,'Moldova','MDA'),
	(142,'Mônaco','MCO'),
	(143,'Mongólia','MNG'),
	(144,'Montenegro','MNE'),
	(145,'Montserrat','MSR'),
	(146,'Marrocos','MAR'),
	(147,'Moçambique','MOZ'),
	(148,'Myanmar','MMR'),
	(149,'Namíbia','NAM'),
	(150,'Nauru','NRU'),
	(151,'Nepal','NPL'),
	(152,'Países Baixos','NLD'),
	(153,'Antillhas Holandesas','ANT'),
	(154,'Nova Caledônia','NCL'),
	(155,'Nova Zelândia','NZL'),
	(156,'Nicarágua','NIC'),
	(157,'Níger','NER'),
	(158,'Nigéria','NGA'),
	(159,'Niue','NIU'),
	(160,'Ilhas Norfolk','NFK'),
	(161,'República Turca de Chipre do Norte','CYP'),
	(162,'Marianas Setentrionais','MNP'),
	(163,'Noruega','NOR'),
	(164,'Omã','OMN'),
	(165,'Paquistão','PAK'),
	(166,'Palau','PLW'),
	(167,'Panamá','PAN'),
	(168,'Papua-Nova Guiné','PNG'),
	(169,'Paraguai','PRY'),
	(170,'Peru','PER'),
	(171,'Filipinas','PHL'),
	(172,'Ilha Pitcaim','PCN'),
	(173,'Polônia','POL'),
	(174,'Portugal','PRT'),
	(175,'Porto Rico','PRI'),
	(176,'Catar','QAT'),
	(177,'Reunion','REU'),
	(178,'Romênia','ROU'),
	(179,'Rússia','RUS'),
	(180,'Ruanda','RWA'),
	(181,'São Vicente e Granadinas','VCT'),
	(182,'São Marinho','SMR'),
	(183,'São Tomé e Príncipe','STP'),
	(184,'Arábia Saudita','SAU'),
	(185,'Senegal','SEN'),
	(186,'Serbia','SRB'),
	(187,'Sérvia e Montenegro','SCG'),
	(188,'Seicheles','SYC'),
	(189,'Serra Leoa','SLE'),
	(190,'Singapura','SGP'),
	(191,'Eslováquia','SVK'),
	(192,'Eslovênia','SVN'),
	(193,'Ilhas Salomão','SLB'),
	(194,'Somália','SOM'),
	(195,'Africa do Sul','ZAF'),
	(196,'Ilhas Geórgia do Sul e Sandwich do Sul','SGS'),
	(197,'Ilhas Sandwich do Sul','SGS'),
	(198,'Espanha','ESP'),
	(199,'Sri Lanka','LKA'),
	(200,'Santa Helena','SHN'),
	(201,'São Cristóvão e Névis','KNA'),
	(202,'Santa Lúcia','LCA'),
	(203,'St Pierre e Miquelon','SPM'),
	(204,'Sudão','SDN'),
	(205,'Suriname','SUR'),
	(206,'Ilhas Svalbard e Jan Mayen','SJM'),
	(207,'Suazilândia','SWZ'),
	(208,'Suécia','SWE'),
	(209,'Suiça','CHE'),
	(210,'Síria','SYR'),
	(211,'Formosa','TWN'),
	(212,'Tadjiquistão','TJK'),
	(213,'Tanzânia','TZA'),
	(214,'Tailândia','THA'),
	(215,'Gâmbia','GMB'),
	(216,'Timor Leste','TM'),
	(217,'Togo','TGO'),
	(218,'Tokelau','TKL'),
	(219,'Tonga','TON'),
	(220,'Trinidad e Tobago','TTO'),
	(221,'Tristão da Cunha','SHN'),
	(222,'Tunísia','TUN'),
	(223,'Turquia','TUR'),
	(224,'Turcomenistão','TKM'),
	(225,'Ilhas Turks e Caicos','TCA'),
	(226,'Tuvalu','TUV'),
	(227,'Uganda','UGA'),
	(228,'Ucrânia','UKR'),
	(229,'Emirados Árabes Unidos','ARE'),
	(230,'Uruguai','URY'),
	(231,'Uzbequistão','UZB'),
	(232,'Vanuatu','VUT'),
	(233,'Venezuela','VEN'),
	(234,'Vietnã','VNM'),
	(235,'Ilhas Virgens Britânicas','VGB'),
	(236,'Ilhas Virgens Americanas','VIR'),
	(237,'Ilhas Wallis e Futuna','WLF'),
	(238,'Cisjordânia','WBA'),
	(239,'Sahara do Oeste','ESH'),
	(240,'Samoa','WSM'),
	(241,'Iêmen','YEM'),
	(242,'Jugoslávia','YUG'),
	(243,'Zaire','ZAR'),
	(244,'Zâmbia','ZMB'),
	(245,'Zimbábue','ZWE');